### ISSUE TITLE
Some questions about your published article

### ISSUE THREAD

**Issue by solo-Shen** [polimi-ispl/nah-cnn#1]
Hi, Dr. Olivieri！After reading your article for the first time, I have several questions as listed below:
(1) You have showed zH where the hologram plane is palced. However you do not show the dimentions of this plane in x and y. Is the  hologram plane smaller than any rectangular plates and what are the specific dimentions？ 
(2) In Fig.3, you clearly show reconstruction examples of the three different boundary conditions as well as three rectangular plates with different dimentions. Are these dimensions shown by your network or known in advance(that is, the network just shows a velcony image shaped as 16×64, we humans plot the figures according to the dimensions from the test dataset)?
(3) About the location of the rectangular plates, are the rectangular plates located at a fixed position(center faced or whatever) or a random postion?

**Comment by MarcoOlly** [comment]
Thank you for your interest in our recent paper.
Here below I will answer to your questions:

(1) The dimensions of the hologram plane perfectly match the dimensions of the rectangular plate, Lx and Ly. Hence, the x and y dimensions change according the specific plate under study.
Since we fixed the number of measurement points to 1024, the sampling steps used to define the hologram grid will change to cover the entire Lx and Ly dimensions. 

(2) The network does not know a priori information regarding the plate (such that dimensions, natural frequency, etc) 
It predicts only the input-output mapping between images of 16x64 points. 
Notice that, also with reference to the answer 1, each image has the same number of points (1024), but in practice they have different resolutions (since the sampling steps change based on the plate dimensions). 
About the Fig. 3, the depicted examples are not scaled, but they are simply the analysed images 16x64 by the network. 
The dimensions, boundary conditions, frequencies and all the information related to each reconstruction is stored only for our analysis purposes.

(3) In the caption of Fig. 1, we specified the location of the reference system. In particular, the bottom-left corner of each plate is placed in the origin of the Cartesian reference system. 
Based on this decision, the measurement grids are defined consequently.

Kind regards.
Marco Olivieri
